// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_int from "rescript/lib/es6/js_int.js";
import * as Core__Math from "@rescript/core/src/Core__Math.res.mjs";

function make(label) {
  return {
          id: Core__Math.Int.random(0, Js_int.max),
          done: false,
          label: label
        };
}

export {
  make ,
}
/* No side effect */
